{% set name = "lm-format-enforcer" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lm_format_enforcer-{{ version }}.tar.gz
  sha256: b3433c50674045b0e46cd53e5016aa3aa1ba2740411802f57441a4c80d3f9606

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.1.0
    - pip
  run:
    - python >=3.8,<4.0
    - pydantic >=1.10.8
    - interegular >=0.3.2
    - packaging
    - pyyaml

test:
  imports:
    - lmformatenforcer
  commands:
    - pip check
  requires:
    - pip
    - numpy >=1.21.0

about:
  home: https://github.com/noamgat/lm-format-enforcer
  summary: Enforce the output format (JSON Schema, Regex etc) of a language model
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
